import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/layout/Navbar';
import { Almarai } from "next/font/google";

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-almarai", // تعريف متغير للخط
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    // أضفنا almarai.variable هنا ليكون متاحاً عالمياً
   <html lang="ar" dir="ltr" className={`${almarai.variable} bg-[#0F172A]`}>
      <body className="bg-[#0F172A] min-h-screen vc-init"> 
        <Navbar />
         <div> 
          {children}
        </div>
      </body>
    </html>
  );
}