import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Almarai } from "next/font/google";
// استورد الـ Wrapper الجديد
import { NavbarWrapper } from '@/components/layout/NavbarWrapper'; 

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-almarai",
});

// ... باقي الإعدادات (Geist) تبقى كما هي

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
   <html lang="ar" dir="ltr" className={`${almarai.variable} bg-[#0F172A]`}>
      <body className="bg-[#0F172A] min-h-screen vc-init"> 
        {/* استخدم الـ Wrapper هنا */}
        <NavbarWrapper />
         <div> 
          {children}
        </div>
      </body>
    </html>
  );
}